spring:
  profiles: dev #开发环境
  label: master
  application:
    name: springcloud-study-config-client
server:
  port: 3355
#客户端注册进eureka服务列表
eureka:
  client:
    service-url:
      defaultZone: eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    #服务实例名称修改
    instance-id: springcloud-study-config-client-3355
    #访问路径显示IP地址
    prefer-ip-address: true
